### ISSUE TITLE
500 during xls bulk import when ostype does not exist

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#121]
1. Set os type in xls to anything nonexistent.
2. Import the xls and watch the 500 error appear in GUI
3. Observe this in logs:
<pre>
2017-03-23 09:48:03,511 ERROR [django.request]: Internal Server Error: /servers/add/import/
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 24, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 69, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/erigones/gui/vm/views.py", line 393, in add_import_form
    status, html_table[vm] = vm_define_all(request, html_table[vm])
  File "/opt/erigones/gui/vm/utils.py", line 266, in vm_define_all
    if i == 0 and vm['ostype'] in Vm.ZONE:
KeyError: 'ostype'
</pre>

**Comment by ricco386** [comment]
PR #132 close this issue
