### ISSUE TITLE
500 when adding vm as superadmin to the "admin" datacenter

### ISSUE THREAD

**Issue by secult** [erigones/esdc-ce#136]
When adding a new vm to the "admin" datacenter with a superadmin user, but not the default "admin" user, I'm getting a 500.
```
2017-03-30 13:06:16,536 DEBUG [vms.middleware]: "POST /servers/add/settings/" user="palo" dc="admin" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin'])
2017-03-30 13:06:16,566 INFO [gui.models.user]: Loading SuperAdmin IDs into cache: set([1, 7, 10, 11, 13, 15])
2017-03-30 13:06:16,582 INFO [gui.models.user]: Loading Admin IDs for DC "admin" into cache: set([11])
2017-03-30 13:06:16,599 INFO [gui.forms]: Calling API view POST vm_define((u'testjhjh.lan',), data={'node': 'phys1.office.eeee.com', 'mdata': {}, 'ram': 384, 'monitored': True, 'monitoring_hostgroups': [], 'tags': '', 'zfs_io_priority': 100, 'hostname': u'testjhjh.lan', 'snapshot_limit_manual': None, 'owner': u'palo', 'installed': False, 'alias': u'testpalo', 'vcpus': 1, 'template': None, 'snapshot_size_limit': None, 'ostype': 1, 'zpool': u'zones', 'monitoring_templates': [], 'cpu_shares': 100}) by user palo in DC admin
2017-03-30 13:06:16,601 DEBUG [api.decorators]: "POST vm_define (/servers/add/settings/)" user="palo" dc="admin" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin'])
2017-03-30 13:06:16,601 DEBUG [api.decorators]: "POST vm_define (/servers/add/settings/)" user="palo" dc="admin" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin'])
2017-03-30 13:06:16,626 ERROR [api.views]: get() returned more than one User -- it returned 2!
Traceback (most recent call last):
  File "/opt/erigones/api/views.py", line 484, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 212, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/api/vm/define/views.py", line 224, in vm_define
    return VmDefineView(request).response(vm, data, hostname_or_uuid=hostname_or_uuid)
  File "/opt/erigones/api/api_views.py", line 98, in response
    return fun(*args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/erigones/api/vm/define/vm_define.py", line 140, in post
    if ser.is_valid():
  File "/opt/erigones/api/serializers.py", line 647, in is_valid
    return not self.errors
  File "/opt/erigones/api/serializers.py", line 639, in errors
    ret = self.from_native(data, files)
  File "/opt/erigones/api/serializers.py", line 461, in from_native
    attrs = self.restore_fields(data, files)
  File "/opt/erigones/api/serializers.py", line 375, in restore_fields
    field.field_from_native(data, files, field_name, reverted_data)
  File "/opt/erigones/api/relations.py", line 222, in field_from_native
    into[(self.source or field_name)] = self.from_native(value)
  File "/opt/erigones/api/relations.py", line 337, in from_native
    return self.queryset.get(**{self.slug_field: data})
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one User -- it returned 2!
2017-03-30 13:06:16,628 ERROR [django.request]: Internal Server Error: /servers/add/settings/
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 69, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/vm/views.py", line 427, in add_settings_form
    return settings_form(request, None)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 69, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/erigones/gui/vm/views.py", line 454, in settings_form
    status = form.save(action=action, args=(form.current_hostname,))
  File "/opt/erigones/gui/forms.py", line 299, in save
    res = self.api_call(action, self._obj, self._request, args=args, data=data)
  File "/opt/erigones/gui/forms.py", line 276, in api_call
    return call_api_view(request, method, cls._api_call.__func__, *args, data=dict(data), log_response=True)
  File "/opt/erigones/api/utils/views.py", line 21, in call_api_view
    res = fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/erigones/api/views.py", line 487, in dispatch
    response = self.handle_exception(exc)
  File "/opt/erigones/api/views.py", line 454, in handle_exception
    raise exc
MultipleObjectsReturned: get() returned more than one User -- it returned 2!
```

**Comment by dn0** [comment]
Wow, this is very strange.
