### ISSUE TITLE
User email address validation problem

### ISSUE THREAD

**Issue by mbag** [erigones/esdc-ce#14]
Characters allowed in email address field when registering are not the same as characters checked by url regex. 
Definitive solution TBD in comments.

```
Traceback (most recent call last):

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/opt/erigones/gui/decorators.py", line 24, in wrap
    return fun(request, *args, **kwargs)

  File "/opt/erigones/gui/decorators.py", line 53, in wrap
    return fun(request, *args, **kwargs)

  File "/opt/erigones/gui/dc/user/views.py", line 67, in dc_user_list
    return render(request, 'gui/dc/user_list.html', context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/defaulttags.py", line 203, in render
    nodelist.append(node.render(context))

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 536, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))

  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 456, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
```

NoReverseMatch: Reverse for 'dc_user_profile' with arguments '()' and keyword arguments '{u'username': u'user+test@erigones.com'}' not found. 1 pattern(s) tried: ['dc/user/(?P<username>[A-Za-z0-9\\@\\._-]+)/profile/$']

**Comment by dn0** [comment]
Current regex for username: `[A-Za-z0-9\@\._-]+`
Suggested new regex: `[a-zA-Z0-9_\.+-][a-zA-Z0-9_\.+-@]+`

Also the email/username should be checked against this new regex when validating user input from registration, so that we don't register an invalid username.

**Comment by ricco386** [comment]
Submitted PR #17

**Comment by ricco386** [comment]
PR #17 has been merged
