### ISSUE TITLE
Server error when adding multiple IPs from command line

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#177]
Cmd:
```bash
es create /network/int1/ip -ips 'json::["10.100.200.bad","10.100.200.ip"]'
```

Traceback:
```python
2017-06-11 10:58:36,332 ERROR [api.views]: invalid input syntax for type inet: "10.100.200.bad "
LINE 1: ...f-8ffa-430b14866a1b' AND "vms_ipaddress"."ip" IN ('10.100.20...
                                                             ^
Traceback (most recent call last):
  File "/opt/erigones/api/views.py", line 484, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 212, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/api/network/ip/views.py", line 37, in net_ip_list
    return NetworkIPView(request, name, None, data, many=True).response()
  File "/opt/erigones/api/api_views.py", line 98, in response
    return fun(*args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/erigones/api/network/ip/api_views.py", line 113, in post
    if self.ip.exists():  # SELECT count(*) from IPAddress
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/query.py", line 586, in exists
    return self.query.has_results(using=self.db)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/sql/query.py", line 484, in has_results
    return compiler.has_results()
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 811, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: invalid input syntax for type inet: "10.100.200.bad "
LINE 1: ...f-8ffa-430b14866a1b' AND "vms_ipaddress"."ip" IN ('10.100.20...
```

**Comment by mbag** [comment]
Merged
