### ISSUE TITLE
Admin can not add SSH key for user.

### ISSUE THREAD

**Issue by ricco386** [erigones/esdc-ce#18]
Super admit is modify user, and add SSH key for user raises exception:

```
2016-12-12 16:40:28,270 ERROR [api.views]: Invalid field name(s) given in select_related: 'owner'. Choices are: dc_bound, default_dc, userprofile, auth_token
Traceback (most recent call last):
  File "/home/ricco/Erigones/esdc-ce/api/views.py", line 484, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/api/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/api/decorators.py", line 212, in wrap
    return fun(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/api/accounts/user/sshkey/views.py", line 112, in sshkey_manage
    return UserSshkeyView(request, username, title, data).response()
  File "/home/ricco/Erigones/esdc-ce/api/accounts/user/sshkey/api_views.py", line 22, in __init__
    user = get_user(request, username, exists_ok=True, noexists_fail=True)
  File "/home/ricco/Erigones/esdc-ce/api/accounts/user/utils.py", line 29, in get_user
    return get_virt_object(request, User, get_attrs={'username': username}, where=where, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/api/utils/db.py", line 140, in get_virt_object
    obj = get_object(request, model, get_attrs, sr=sr, pr=pr, extra=extra, where=where, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/api/utils/db.py", line 39, in get_object
    obj = qs.filter(where).get(**attrs)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 378, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 48, in pre_sql_setup
    self.setup_query()
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 39, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 206, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 754, in get_related_selections
    ', '.join(_get_field_choices()) or '(none)',
FieldError: Invalid field name(s) given in select_related: 'owner'. Choices are: dc_bound, default_dc, userprofile, auth_token
2016-12-12 16:40:28,275 ERROR [django.request]: Internal Server Error: /dc/user/richard.kellner+test@erigones.com/profile/ssh_key/add/form/
Traceback (most recent call last):
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/gui/decorators.py", line 24, in wrap
    return fun(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/gui/decorators.py", line 81, in wrap
    return fun(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/gui/decorators.py", line 69, in wrap
    return fun(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/gui/dc/user/views.py", line 230, in dc_user_profile_sshkey_modal_form
    status = sform.save(action='create', args=(user.username, sform.cleaned_data['name']))
  File "/home/ricco/Erigones/esdc-ce/gui/forms.py", line 298, in save
    res = self.api_call(action, self._obj, self._request, args=args, data=data)
  File "/home/ricco/Erigones/esdc-ce/gui/forms.py", line 275, in api_call
    return call_api_view(request, method, cls._api_call.__func__, *args, data=dict(data), log_response=True)
  File "/home/ricco/Erigones/esdc-ce/api/utils/views.py", line 21, in call_api_view
    res = fun(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/envs/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ricco/Erigones/esdc-ce/api/views.py", line 487, in dispatch
    response = self.handle_exception(exc)
  File "/home/ricco/Erigones/esdc-ce/api/views.py", line 454, in handle_exception
    raise exc
FieldError: Invalid field name(s) given in select_related: 'owner'. Choices are: dc_bound, default_dc, userprofile, auth_token
```

**Comment by dn0** [comment]
Missing changelog :)
