### ISSUE TITLE
SMS sending error

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#348]
```
2018-01-31 11:59:56,904 ERROR [api.sms.views]: 
Traceback (most recent call last):
  File "/opt/erigones/api/sms/views.py", line 40, in internal_send
    expire_hours=dc1_settings.SMS_EXPIRATION_HOURS)
  File "/opt/erigones/api/sms/smsapi/views.py", line 66, in sms_send
    assert username and password
AssertionError
```

**Comment by dn0** [comment]
This is expected behavior when SMS configuration is missing.
