### ISSUE TITLE
Exception when running _log_mon_usergroup_action

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#360]
```
[INFO/MainProcess] api.mon.vm.tasks.mon_vm_sync[7i7d1-abcdef-4444-5555-abcd]: [InternalZabbix:main] Saving zabbix host info into VM ..........
[ERROR/MainProcess] Set changed size during iteration
Traceback (most recent call last):
  File "/opt/erigones/api/decorators.py", line 279, in wrap
    return fun(*args, **kwargs)
  File "/opt/erigones/api/mon/alerting/tasks.py", line 56, in _log_mon_usergroup_action
    for user_name in users:
RuntimeError: Set changed size during iteration
[ERROR/MainProcess] Got exception when running _log_mon_usergroup_action(((0, <frozendict {0: set([]), 1: set([u'aaa', u'bbb']), 2: set([u'bbb']), 3: set([])}>), <api.mon.backends.zabbix.monitor.Zabbix object at 0x547d050>, u'7i7d1-123456-6789-1011-abcd', u'....', u'main'), {}): Set changed size during iteration.
```

**Comment by dn0** [comment]
Related to #94
