### ISSUE TITLE
Domain can't dc_bound after it was created

### ISSUE THREAD

**Issue by klebed** [erigones/esdc-ce#448]
Domain can't be bound to datacenter after in was created, it bounds only upon creation.
DC version 4.1
Steps to reproduce - create not bound domain, then attach it to one datacenter, then try to update it with dc_bound = true.

It results with following errors in mgmt log:
```
2019-08-24 10:34:19,395 DEBUG [gui.forms]: SerializerForm._has_changed [dc_bound]: "False" (<type 'bool'>) != "True" (<type 'bool'>)
2019-08-24 10:34:19,395 INFO [gui.forms]: Calling API view PUT dns_domain((u'testdomain.local',), data={'dc_bound': True}) by user admin in DC test
2019-08-24 10:34:19,398 DEBUG [api.decorators]: "PUT dns_domain (/dc/dns/form/admin/)" user="admin" dc="main" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin', 'monitoring_admin'])
2019-08-24 10:34:19,404 ERROR [api.views]: Database is trying to update a relational field of type IntegerField with a value of type Dc. Make sure you are setting the correct relations
Traceback (most recent call last):
  File "/opt/erigones/api/views.py", line 484, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 94, in handler
    return func(*args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 226, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 259, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/api/dns/domain/views.py", line 140, in dns_domain
    return DomainView(request, name, data).response()
  File "/opt/erigones/api/api_views.py", line 100, in response
    return fun(*args, **kwargs)
  File "/opt/erigones/api/dns/domain/api_views.py", line 106, in put
    ser.object.save()
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1028, in as_sql
    (field.__class__.__name__, val.__class__.__name__))
TypeError: Database is trying to update a relational field of type IntegerField with a value of type Dc. Make sure you are setting the correct relations
2019-08-24 10:34:19,424 ERROR [django.request]: Internal Server Error: /dc/dns/form/admin/
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 25, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 82, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 70, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 259, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/dc/dns/views.py", line 134, in admin_domain_form
    status = form.save(args=args)
  File "/opt/erigones/gui/forms.py", line 306, in save
    res = self.api_call(action, self._obj, self._request, args=args, data=data)
  File "/opt/erigones/gui/forms.py", line 283, in api_call
    return call_api_view(request, method, cls._api_call.__func__, *args, data=dict(data), log_response=True)
  File "/opt/erigones/api/utils/views.py", line 27, in call_api_view
    res = fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/erigones/api/views.py", line 487, in dispatch
    response = self.handle_exception(exc)
  File "/opt/erigones/api/views.py", line 454, in handle_exception
    raise exc
TypeError: Database is trying to update a relational field of type IntegerField with a value of type Dc. Make sure you are setting the correct relations
```
UPD: And then it can't be deleted.

```
2019-08-24 10:49:10,606 INFO [gui.forms]: Calling API view DELETE dns_domain((u'testdomain.local',), data={'name': u'testdomain.local', 'access': 3, 'dc_bound': False, 'owner': u'admin', 'type': u'MASTER', 'desc': u''}) by user admin in DC powercomp
2019-08-24 10:49:10,608 DEBUG [api.decorators]: "DELETE dns_domain (/dc/dns/form/admin/)" user="admin" dc="main" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin', 'monitoring_admin'])
2019-08-24 10:49:10,626 ERROR [api.views]: Domain matching query does not exist.
Traceback (most recent call last):
  File "/opt/erigones/api/views.py", line 484, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 94, in handler
    return func(*args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 226, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 259, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/api/dns/domain/views.py", line 140, in dns_domain
    return DomainView(request, name, data).response()
  File "/opt/erigones/api/api_views.py", line 100, in response
    return fun(*args, **kwargs)
  File "/opt/erigones/api/dns/domain/api_views.py", line 143, in delete
    domain.delete()
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/base.py", line 896, in delete
    collector.delete()
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/deletion.py", line 314, in delete
    sender=model, instance=obj, using=self.using
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/erigones/pdns/models/record.py", line 318, in post_delete_record
    cls.increment_SOA_serial(instance)
  File "/opt/erigones/pdns/models/record.py", line 290, in increment_SOA_serial
    soa_rec = cls.objects.get(type=cls.SOA, domain_id=instance.domain.id)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/fields/related.py", line 614, in __get__
    rel_obj = qs.get()
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Domain matching query does not exist.
2019-08-24 10:49:10,628 ERROR [django.request]: Internal Server Error: /dc/dns/form/admin/
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 25, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 82, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/decorators.py", line 70, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/erigones/api/decorators.py", line 259, in wrap
    return fun(request, *args, **kwargs)
  File "/opt/erigones/gui/dc/dns/views.py", line 134, in admin_domain_form
    status = form.save(args=args)
  File "/opt/erigones/gui/forms.py", line 306, in save
    res = self.api_call(action, self._obj, self._request, args=args, data=data)
  File "/opt/erigones/gui/forms.py", line 283, in api_call
    return call_api_view(request, method, cls._api_call.__func__, *args, data=dict(data), log_response=True)
  File "/opt/erigones/api/utils/views.py", line 27, in call_api_view
    res = fun(request, *args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/erigones/envs/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/erigones/api/views.py", line 487, in dispatch
    response = self.handle_exception(exc)
  File "/opt/erigones/api/views.py", line 454, in handle_exception
    raise exc
DoesNotExist: Domain matching query does not exist.
```

UPD2: Deleted after wiping all the records inside domain.

**Comment by YanChii** [comment]
Ping @dn0
