### ISSUE TITLE
Unable to use new lx-centos-8

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#579]
Hi 
I downloaded the new lx image from smartos central repo 
When I try to use it I got : 
<html>
<body>

Got bad return code (1). Error: Invalid value(s) for: image_uuid Unable to start VM dnav: bad statusCode: 404
--

</body>
</html>

If I change the image to an old lx centos 7 it works.
Paolo

**Comment by YanChii** [comment]
Hi @marcheschi 

Which image did you download? 
The latest LX image I see in Joyent's repo is `lx-centos-8` (`ef0af4a0-0a05-4852-b891-53430706bc5b`). That one really has a problem but it doesn't seem to be related to your issue:
```
Cannot import required image lx-centos-8-20211220 to node sb32.danube.cloud (428: Image requires newer node version) (424)
```
The next one (`ubuntu-20.04`, `0bf06d4d-b62f-4b3b-b560-3cd258df2070`) works without issue.

Pls try to delete the image from DC repository and re-download it.

Jan

**Comment by marcheschi** [comment]
Hi @YanChii 
I tried to remove and download again, but the result is the same, I looked in the mgmt.log
It seems there is a previous error `  "lx-centos-8" was not found in image sources'`
```
[2022-04-05 07:35:42,369: ERROR/MainProcess] api.node.image.tasks.node_image_cb[9e1u3-2b816b75-6ac3-4467-be24]: {u'message': u'imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:35:38.684211', 'caller': u'9e1u3-36ca9ea8-d
8ad-4bdc-9fdc', u'apiview': {u'zpool': u'zones', u'hostname': u'node03ms.hypervisor.ms.fgm', u'view': u'node_image', u'method': u'POST', u'name': u'lx-centos-8'}, u'nolog': False, u'finish_time': u'2022-04-05T07:35:39.167042', u'msg': u'Import image on node storage', u'nodestorage_id': 19}, 'detail': u'Got bad return code (1). Error:
 imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources'}
Traceback (most recent call last):
  File "/opt/erigones/api/task/utils.py", line 250, in inner
    return fun(result, task_id, *args, **kwargs)
  File "/opt/erigones/api/node/image/tasks.py", line 59, in node_image_cb
    raise TaskException(result, 'Got bad return code (%s). Error: %s' % (result['returncode'], msg))
TaskException: {u'message': u'imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:35:38.684211', 'caller': u'9e1u3-36ca9ea8-d8ad-4bdc-9fdc', u'apiview': {u'zpool': u'zones', u'hostname': u'node03ms.hypervisor.ms.fgm', u'view': u'node_image', u'method': u'POST', u'name': u'lx-centos-8'}, u'nolog': False, u'finish_time': u'2022-04-05T07:35:39.167042', u'msg': u'Import image on node storage', u'nodestorage_id': 19}, 'detail': u'Got bad return code (1). Error: imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources'}
[2022-04-05 07:35:42,370: ERROR/MainProcess] api.node.image.tasks.node_image_cb[9e1u3-2b816b75-6ac3-4467-be24]: Task 9e1u3-36ca9ea8-d8ad-4bdc-9fdc failed
[2022-04-05 07:35:42,544: INFO/MainProcess] Task 9e1u3-36ca9ea8-d8ad-4bdc-9fdc removed from esdc:tasks-1
[2022-04-05 07:35:42,629: ERROR/MainProcess] Task api.node.image.tasks.node_image_cb[9e1u3-2b816b75-6ac3-4467-be24] raised unexpected: TaskException({u'message': u'imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:35:38.684211', 'caller': u'9e1u3-36ca9ea8-d8ad-4bdc-9fdc', u'apiview': {u'zpool': u'zones', u'hostname': u'node03ms.hypervisor.ms.fgm', u'view': u'node_image', u'method': u'POST', u'name': u'lx-centos-8'}, u'nolog': False, u'finish_time': u'2022-04-05T07:35:39.167042', u'msg': u'Import image on node storage', u'nodestorage_id': 19}, 'detail': u'Got bad return code (1). Error: imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources'},)
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/erigones/que/mgmt.py", line 48, in __call__
    return super(MgmtCallbackTask, self).__call__(*args, **kwargs)  # run()
  File "/opt/erigones/envs/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/erigones/api/task/utils.py", line 284, in inner
    raise e
TaskException: {u'message': u'imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:35:38.684211', 'caller': u'9e1u3-36ca9ea8-d8ad-4bdc-9fdc', u'apiview': {u'zpool': u'zones', u'hostname': u'node03ms.hypervisor.ms.fgm', u'view': u'node_image', u'method': u'POST', u'name': u'lx-centos-8'}, u'nolog': False, u'finish_time': u'2022-04-05T07:35:39.167042', u'msg': u'Import image on node storage', u'nodestorage_id': 19}, 'detail': u'Got bad return code (1). Error: imgadm import: error (ActiveImageNotFound): an active image "lx-centos-8" was not found in image sources'}
[2022-04-05 07:35:43,054: INFO/MainProcess] Received task: api.vm.replica.tasks.vm_replica_sync_cb[7i7d1-ff08c063-4e32-4f8e-9864] expires:[2022-04-05 07:37:43.025326+00:00]
[2022-04-05 07:35:43,226: INFO/MainProcess] Task api.vm.replica.tasks.vm_replica_sync_cb[7i7d1-ff08c063-4e32-4f8e-9864] succeeded in 0.169324382674s: {u'synced_disks': [[u'zones/4603674d-0562-400b-a920-3d4a94497477/disk0', u'zones/e59bd527-e885-4eb4-91ba-6e928acf2b6d/disk0']],...
[2022-04-05 07:36:41,360: INFO/MainProcess] Received task: api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798]
[2022-04-05 07:36:41,372: WARNING/MainProcess] api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798]: Whoa! Parent task 9e9d3-b0551311-823c-450a-89da has not finished yet with status=SUCCESS. Waiting 1 second (1), before running vm_create_cb
[2022-04-05 07:36:42,373: INFO/MainProcess] api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798]: Parent task 9e9d3-b0551311-823c-450a-89da has finished with status=SUCCESS. Running vm_create_cb
[2022-04-05 07:36:42,407: ERROR/MainProcess] api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798]: Found nonzero returncode in result from POST vm_manage(c1adee8d-fd65-4db3-8508-44c3ccd30203). Error: Invalid value(s) for: image_uuid
Unable to start VM dnav2: bad statusCode: 404
[2022-04-05 07:36:42,745: ERROR/MainProcess] api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798]: {u'json': u'', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:36:39.919540', 'caller': u'9e9d3-b0551311-823c-450a-89da', u'apiview': {u'hostname': u'dnav2', u'deploy': False, u'recreate': False, u'method': u'POST', u'resize': True, u'view': u'vm_manage'}, u'nolog': False, u'finish_time': u'2022-04-05T07:36:41.311230', u'vm_uuid': u'c1adee8d-fd65-4db3-8508-44c3ccd30203', u'msg': u'Create server'}, u'message': u'Invalid value(s) for: image_uuid\nUnable to start VM dnav2: bad statusCode: 404', 'detail': u'Got bad return code (1). Error: Invalid value(s) for: image_uuid\nUnable to start VM dnav2: bad statusCode: 404'}
Traceback (most recent call last):
  File "/opt/erigones/api/task/utils.py", line 250, in inner
    return fun(result, task_id, *args, **kwargs)
  File "/opt/erigones/api/vm/base/tasks.py", line 152, in vm_create_cb
    raise TaskException(result, 'Got bad return code (%s). Error: %s' % (result['returncode'], msg))
TaskException: {u'json': u'', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:36:39.919540', 'caller': u'9e9d3-b0551311-823c-450a-89da', u'apiview': {u'hostname': u'dnav2', u'deploy': False, u'recreate': False, u'method': u'POST', u'resize': True, u'view': u'vm_manage'}, u'nolog': False, u'finish_time': u'2022-04-05T07:36:41.311230', u'vm_uuid': u'c1adee8d-fd65-4db3-8508-44c3ccd30203', u'msg': u'Create server'}, u'message': u'Invalid value(s) for: image_uuid\nUnable to start VM dnav2: bad statusCode: 404', 'detail': u'Got bad return code (1). Error: Invalid value(s) for: image_uuid\nUnable to start VM dnav2: bad statusCode: 404'}
[2022-04-05 07:36:42,746: ERROR/MainProcess] api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798]: Task 9e9d3-b0551311-823c-450a-89da failed
[2022-04-05 07:36:42,911: INFO/MainProcess] Task 9e9d3-b0551311-823c-450a-89da removed from esdc:tasks-9
[2022-04-05 07:36:42,919: ERROR/MainProcess] Task api.vm.base.tasks.vm_create_cb[9e9d3-565c2ff2-24ea-4deb-9798] raised unexpected: TaskException({u'json': u'', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:36:39.919540', 'caller': u'9e9d3-b0551311-823c-450a-89da', u'apiview': {u'hostname': u'dnav2', u'deploy': False, u'recreate': False, u'method': u'POST', u'resize': True, u'view': u'vm_manage'}, u'nolog': False, u'finish_time': u'2022-04-05T07:36:41.311230', u'vm_uuid': u'c1adee8d-fd65-4db3-8508-44c3ccd30203', u'msg': u'Create server'}, u'message': u'Invalid value(s) for: image_uuid\nUnable to start VM dnav2: bad statusCode: 404', 'detail': u'Got bad return code (1). Error: Invalid value(s) for: image_uuid\nUnable to start VM dnav2: bad statusCode: 404'},)
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/erigones/que/mgmt.py", line 48, in __call__
    return super(MgmtCallbackTask, self).__call__(*args, **kwargs)  # run()
  File "/opt/erigones/envs/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/erigones/api/task/utils.py", line 284, in inner
    raise e
TaskException: {u'json': u'', u'returncode': 1, u'meta': {u'exec_time': u'2022-04-05T07:36:39.919540', 'caller': u'9e9d3-b0551311-823c-450a-89da', u'apiview': {u'hostname': u'dnav2', u'deploy': False, u'recreate': False, u'method': u'POST', u'resize': True, u'view': u'vm_manage'}, u'nolog': False, u'finish_time': u'2022-04-05T07:36:4
 
```

Paolo

**Comment by YanChii** [comment]
When you look into `img01.local`, inside `/datasets`, is the image present? You can find it according to it's original UUID in Joyent's repo (or by creation date). You can verify it's the right image by checking the `manifest` file inside UUID directory.

It seems like the image is not present there.

And, if it's present, pls try downloading it manually to a node using `imgadm` command.

**Comment by marcheschi** [comment]
Yes it is not present there, there is plenty of space available. Maybe there is some problem in downloading the image from the repo, but from the interface it seems ok

**Comment by marcheschi** [comment]
Hi
I'm unable to import the new ubuntu focal image .
From the interface it says it is imported but when I try to use it it gives me an error.
infoact from mgmt.log file:
TaskException: {u'message': u'imgadm import: error (NoSources): imgadm has no configured sources', u'returncode': 1, u'meta': {u'exec_time': u'2022-05-05T12:35:35.786408', 'caller': u'9e1u1-c3c6210d-6375-4592-9581', u'apiview': {u'zpool': u'zones', u'hostname': u'iperione.hypervisor.pi.fgm', u'view': u'node_image', u'method': u'POST', u'name': u'ubuntu-focal-uefi_1'}, u'nolog': False, u'finish_time': u'2022-05-05T12:35:36.631306', u'msg': u'Import image on node storage', u'nodestorage_id': 30}, 'detail': u'Got bad return code (1). Error: imgadm import: error (NoSources): imgadm has no configured sources'}

This is a old smartos server repurposed with Danubecloud, I did the unattended install and the new server is now part of DC.

But it seems that no sources are present.

**Comment by marcheschi** [comment]
Maybe some error here @YanChii 
![image](https://user-images.githubusercontent.com/3910408/166932065-2cda02eb-da03-4ac0-9e0f-34ab70799c20.png)

maybe the VMS_IMAGE_VM must be img01.local ?

**Comment by marcheschi** [comment]
Yes I think this was the problem

**Comment by YanChii** [comment]
Hi @marcheschi 
Yes, the image VM name should be configured. The setting is there by default, not sure why it wasn't in your case.
Jan

**Comment by marcheschi** [comment]
Hi maybe someone unconfigured it by error!
