### ISSUE TITLE
KeyError: 'get_image_manifes_url'

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#8]
Critical typo found in POST imagestore_image_manage:
```
Traceback (most recent call last):
  File "/Users/dano/erigones/esdc-ce/api/views.py", line 484, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/dano/erigones/esdc-ce/api/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/Users/dano/erigones/esdc-ce/api/decorators.py", line 212, in wrap
    return fun(request, *args, **kwargs)
  File "/Users/dano/erigones/esdc-ce/api/imagestore/image/views.py", line 63, in imagestore_image_manage
    return ImageStoreImageView(request, name, uuid, data).response()
  File "/Users/dano/erigones/esdc-ce/api/api_views.py", line 98, in response
    return fun(*args, **kwargs)
  File "/Users/dano/erigones/esdc-ce/api/imagestore/image/api_views.py", line 54, in post
    data['manifest_url'] = self.repo.get_image_manifes_url(img['uuid'])
  File "/Users/dano/erigones/esdc-ce/vms/models/base.py", line 59, in __getattr__
    return self._data[key]
KeyError: 'get_image_manifes_url'
```

**Comment by dn0** [comment]
Steps to reproduce the problem:

1. Make sure you a working image repository with images available (either via GUI or API)
2. Try to import image via API, e.g. `es create /imagestore/danubecloud/image/026b627c-3ef2-4517-8d76-34eb1f90d508`

Note: You can list available images via `es get /imagestore/danubecloud/image`
